package com.example.myapplication.webservice.exluir;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface IWTIServiceEvents
{
    void Starting();
    void Completed(IWTOperationResult result);
}
