package com.example.myapplication.webservice.exluir;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class IWTreprovacao extends IWTtabela implements KvmSerializable
{
    
    public String cpf;
    
    public Integer id;
    
    public IWTmateria materia;
    
    public String matricula;
    
    public String nome;
    
    public String professor;
        

    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,IWTExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);



    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,IWTExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("cpf"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.cpf = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.cpf = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("id"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.id = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.id = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("materia"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.materia = (IWTmateria)__envelope.get(j,IWTmateria.class,false);
            }
            return true;
        }
        if (info.name.equals("matricula"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.matricula = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.matricula = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("nome"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.nome = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.nome = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("professor"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.professor = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.professor = (String)obj;
                }
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.cpf!=null?this.cpf:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.materia!=null?this.materia:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.matricula!=null?this.matricula:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return this.nome!=null?this.nome:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return this.professor!=null?this.professor:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cpf";
            info.namespace= "";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "id";
            info.namespace= "";
        }
        if(propertyIndex==count+2)
        {
            info.type = IWTmateria.class;
            info.name = "materia";
            info.namespace= "";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "matricula";
            info.namespace= "";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nome";
            info.namespace= "";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "professor";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
