package com.example.myapplication.webservice.exluir;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class IWTtabela extends AttributeContainer implements KvmSerializable
{
    
    public ArrayList< java.lang.Object> camposValorUtil =new ArrayList<java.lang.Object >();
    
    public java.lang.Object pk;
        
    private transient java.lang.Object __source;    
    

    
    
    public void loadFromSoap(java.lang.Object paramObj,IWTExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,IWTExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("camposValorUtil"))
        {
            if(obj!=null)
            {
if(this.camposValorUtil==null)
                {
                    this.camposValorUtil = new java.util.ArrayList< java.lang.Object>();
                }
                java.lang.Object j =obj;
                java.lang.Object j1= __envelope.getSpecificType(j);
                this.camposValorUtil.add(j1);            }
            return true;
        }
        if (info.name.equals("pk"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.pk = __envelope.getSpecificType(j);
                    }
                }
                else {
                    this.pk = __envelope.getSpecificType(obj);
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.camposValorUtil.size())
        {
                java.lang.Object camposValorUtil = this.camposValorUtil.get(propertyIndex-(0));
                return camposValorUtil!=null?camposValorUtil:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==0+this.camposValorUtil.size())
        {
            return this.pk!=null?this.pk:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+camposValorUtil.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.camposValorUtil.size())
        {
            info.type = IWTExtendedSoapSerializationEnvelope.getXSDType(camposValorUtil);
            info.name = "camposValorUtil";
            info.namespace= "";
        }
        if(propertyIndex==0+this.camposValorUtil.size())
        {
            info.type = IWTExtendedSoapSerializationEnvelope.getXSDType(pk);
            info.name = "pk";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
