package com.example.myapplication.webservice.cadastrar;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface SACIServiceEvents
{
    void Starting();
    void Completed(SACOperationResult result);
}
