package com.example.myapplication.webservice.alterar;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface FCRIServiceEvents
{
    void Starting();
    void Completed(FCROperationResult result);
}
