package com.example.myapplication.webservice.listar;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.7.0.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface UWCIServiceEvents
{
    void Starting();
    void Completed(UWCOperationResult result);
}
